// Generated by Framer (293632e)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    forwardLoader,
    getFonts,
    getFontsFromSharedStyle,
    Link,
    RichText,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/4Ae2qThangq04M8pP872/7bjimfGvMfXmErlXYpLI/Sz9S4_GWH.js";
import ArrowIcon from "https://framerusercontent.com/modules/EHkF60BuN9UT6F1LfE54/WjunPy35ULkRw45kApcT/m2xQ4XX2C.js";
const ArrowIconFonts = getFonts(ArrowIcon);
const enabledGestures = {
    fToFJNAXK: {
        hover: true
    }
};
const serializationHash = "framer-88DPD";
const variantClassNames = {
    fToFJNAXK: "framer-v-7nicnc"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const I8j5ZcDgy = undefined;
const zRzdSp3NC = undefined;
const aWr3uf33N = undefined;
const MWxLGyIHQ = undefined;
const transition1 = {
    bounce: 0,
    delay: 0,
    duration: .6,
    type: "spring"
};
const matchVariant = (...args) => {
    for (const arg of args) {
        if (arg && typeof arg === "string") return arg;
    }
    return undefined;
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    link,
    newTab,
    smoothScroll,
    text,
    width,
    ...props
}) => {
    return { ...props,
        aWr3uf33N: smoothScroll ? ? props.aWr3uf33N,
        I8j5ZcDgy: link ? ? props.I8j5ZcDgy,
        MWxLGyIHQ: text ? ? props.MWxLGyIHQ ? ? "Discover",
        zRzdSp3NC: newTab ? ? props.zRzdSp3NC
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        MWxLGyIHQ,
        I8j5ZcDgy,
        zRzdSp3NC,
        aWr3uf33N,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "fToFJNAXK",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: I8j5ZcDgy,
                    motionChild: true,
                    nodeId: "fToFJNAXK",
                    openInNewTab: zRzdSp3NC,
                    scopeId: "WdNkl0JPc",
                    smoothScroll: aWr3uf33N,
                    children: /*#__PURE__*/ _jsxs(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-7nicnc",className,classNames)} framer-211ff1`,
                        "data-framer-name": "Link",
                        layoutDependency: layoutDependency,
                        layoutId: "fToFJNAXK",
                        ref: refBinding,
                        style: { ...style
                        },
                        ...addPropertyOverrides({
                            "fToFJNAXK-hover": {
                                "data-framer-name": undefined
                            }
                        }, baseVariant, gestureVariant),
                        children: [ /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-1tblw7z",
                            "data-framer-name": "Line",
                            layoutDependency: layoutDependency,
                            layoutId: "DbZRPOphN",
                            style: {
                                backgroundColor: "var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
                                opacity: 0
                            },
                            variants: {
                                "fToFJNAXK-hover": {
                                    opacity: 1
                                }
                            }
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-1igwnwn",
                                    "data-styles-preset": "Sz9S4_GWH",
                                    dir: "auto",
                                    children: "Discover"
                                })
                            }),
                            className: "framer-byoks2",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "rge0lyAjm",
                            style: {
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline"
                            },
                            text: MWxLGyIHQ,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 18,
                            y: (componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 200) - 0 - 18) / 2),
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-1fau466-container",
                                layoutDependency: layoutDependency,
                                layoutId: "YSmBQb8oW-container",
                                nodeId: "YSmBQb8oW",
                                rendersWithMotion: true,
                                scopeId: "WdNkl0JPc",
                                children: /*#__PURE__*/ _jsx(ArrowIcon, {
                                    height: "100%",
                                    id: "YSmBQb8oW",
                                    layoutId: "YSmBQb8oW",
                                    variant: matchVariant("NwqAfOsnO"),
                                    width: "100%",
                                    ...addPropertyOverrides({
                                        "fToFJNAXK-hover": {
                                            variant: matchVariant("yaT7O5nxk")
                                        }
                                    }, baseVariant, gestureVariant)
                                })
                            })
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-88DPD.framer-211ff1, .framer-88DPD .framer-211ff1 { display: block; }", ".framer-88DPD.framer-7nicnc { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: min-content; }", ".framer-88DPD .framer-1tblw7z { bottom: 0px; flex: none; height: 1px; left: 0px; overflow: hidden; position: absolute; width: 1%; z-index: 1; }", ".framer-88DPD .framer-byoks2 { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }", ".framer-88DPD .framer-1fau466-container { flex: none; height: auto; position: relative; width: auto; }", ".framer-88DPD.framer-v-7nicnc.hover .framer-1tblw7z { width: 100%; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 25
 * @framerIntrinsicWidth 90
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"jCHXI322g":{"layout":["auto","auto"]}}}
 * @framerVariables {"MWxLGyIHQ":"text","I8j5ZcDgy":"link","zRzdSp3NC":"newTab","aWr3uf33N":"smoothScroll"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerWdNkl0JPc = withCSS(Component, css, "framer-88DPD");
export default FramerWdNkl0JPc;
FramerWdNkl0JPc.displayName = "Primary Link";
FramerWdNkl0JPc.defaultProps = {
    height: 25,
    width: 90
};
addPropertyControls(FramerWdNkl0JPc, {
    MWxLGyIHQ: {
        defaultValue: "Discover",
        displayTextArea: false,
        title: "Text",
        type: ControlType.String
    },
    I8j5ZcDgy: {
        title: "Link",
        type: ControlType.Link
    },
    zRzdSp3NC: {
        defaultValue: false,
        title: "New Tab",
        type: ControlType.Boolean
    },
    aWr3uf33N: {
        defaultValue: false,
        title: "Smooth Scroll",
        type: ControlType.Boolean
    }
});
addFonts(FramerWdNkl0JPc, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...ArrowIconFonts, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
FramerWdNkl0JPc.loader = {
    load: (props, context) => {
        const locale = context.locale;
        return Promise.allSettled([forwardLoader(ArrowIcon, {}, context)]);
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerWdNkl0JPc",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "90",
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerColorSyntax": "true",
                "framerVariables": "{\"MWxLGyIHQ\":\"text\",\"I8j5ZcDgy\":\"link\",\"zRzdSp3NC\":\"newTab\",\"aWr3uf33N\":\"smoothScroll\"}",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"jCHXI322g\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicHeight": "25",
                "framerAutoSizeImages": "true",
                "framerComponentViewportWidth": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./WdNkl0JPc.map