// Generated by Framer (2306ade)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getLoadingLazyAtYPosition,
    Image,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const serializationHash = "framer-4hAkk";
const variantClassNames = {
    Z1wnvFaQC: "framer-v-1u4j3me"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const toResponsiveImage = value => {
    if (typeof value === "object" && value !== null && typeof value.src === "string") {
        return value;
    }
    return typeof value === "string" ? {
        src: value
    } : undefined;
};
const transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    image,
    shadow,
    width,
    ...props
}) => {
    return { ...props,
        LjLmFiVQc: image ? ? props.LjLmFiVQc ? ? {
            pixelHeight: 6220,
            pixelWidth: 6220,
            src: "/framerusercontent.com/images/K6cUNifhQFa6qEX3kqNwfqMkiY.jpg?scale-down-to=512",
            srcSet: "/framerusercontent.com/images/K6cUNifhQFa6qEX3kqNwfqMkiY.jpg?scale-down-to=512 512w,/framerusercontent.com/images/K6cUNifhQFa6qEX3kqNwfqMkiY.jpg?scale-down-to=1024 1024w,/framerusercontent.com/images/K6cUNifhQFa6qEX3kqNwfqMkiY.jpg?scale-down-to=2048 2048w,/framerusercontent.com/images/K6cUNifhQFa6qEX3kqNwfqMkiY.jpg?scale-down-to=4096 4096w,/framerusercontent.com/images/K6cUNifhQFa6qEX3kqNwfqMkiY.jpg 6220w"
        },
        zc3QUak_i: shadow ? ? props.zc3QUak_i ? ? "0px 0px 0px 2px var(--token-bf8bd38a-4575-40c0-9459-6a86668113f1, rgb(250, 250, 250))"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        LjLmFiVQc,
        zc3QUak_i,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "Z1wnvFaQC",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1u4j3me", className, classNames),
                    "data-framer-name": "Avatar",
                    layoutDependency: layoutDependency,
                    layoutId: "Z1wnvFaQC",
                    ref: refBinding,
                    style: { ...style
                    },
                    children: /*#__PURE__*/ _jsx(Image, {
                        background: {
                            alt: "",
                            fit: "fill",
                            loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + ((componentViewport ? .height || 32) * .5000000000000002 - 16)),
                            pixelHeight: 400,
                            pixelWidth: 400,
                            sizes: "32px",
                            ...toResponsiveImage(LjLmFiVQc),
                            ...{
                                positionX: "center",
                                positionY: "center"
                            }
                        },
                        className: "framer-1eroy8m",
                        "data-framer-name": "Image",
                        layoutDependency: layoutDependency,
                        layoutId: "fY8r03yF2",
                        style: {
                            "--y2yudj": zc3QUak_i,
                            borderBottomLeftRadius: 1e3,
                            borderBottomRightRadius: 1e3,
                            borderTopLeftRadius: 1e3,
                            borderTopRightRadius: 1e3,
                            boxShadow: "var(--y2yudj)"
                        },
                        transformTemplate: transformTemplate1
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-4hAkk.framer-110wlzh, .framer-4hAkk .framer-110wlzh { display: block; }", ".framer-4hAkk.framer-1u4j3me { height: 32px; overflow: visible; position: relative; width: 1px; }", ".framer-4hAkk .framer-1eroy8m { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 32px); left: 50%; overflow: hidden; position: absolute; top: 50%; width: 32px; will-change: var(--framer-will-change-override, transform); z-index: 1; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 32
 * @framerIntrinsicWidth 1
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"LjLmFiVQc":"image","zc3QUak_i":"shadow"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerYZM3vWqiv = withCSS(Component, css, "framer-4hAkk");
export default FramerYZM3vWqiv;
FramerYZM3vWqiv.displayName = "Client Avatar";
FramerYZM3vWqiv.defaultProps = {
    height: 32,
    width: 1
};
addPropertyControls(FramerYZM3vWqiv, {
    LjLmFiVQc: {
        __defaultAssetReference: "data:framer/asset-reference,K6cUNifhQFa6qEX3kqNwfqMkiY.jpg?originalFilename=photo-1633332755192-727a05c4013d%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwxMXx8aGVhZHNob3R8ZW58MHx8fHwxNzI2ODU5MTAxfDA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
        description: "Upload avatar ",
        title: "Image",
        type: ControlType.ResponsiveImage
    },
    zc3QUak_i: {
        defaultValue: [{
            blur: 0,
            color: 'var(--token-bf8bd38a-4575-40c0-9459-6a86668113f1, rgb(250, 250, 250)) /* {"name":"Gray 5"} */',
            diffusion: .5,
            focus: .5,
            inset: false,
            spread: 2,
            type: "box",
            x: 0,
            y: 0
        }],
        title: "Shadow",
        type: ControlType.BoxShadow
    }
});
addFonts(FramerYZM3vWqiv, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerYZM3vWqiv",
            "slots": [],
            "annotations": {
                "framerColorSyntax": "true",
                "framerDisplayContentsDiv": "false",
                "framerVariables": "{\"LjLmFiVQc\":\"image\",\"zc3QUak_i\":\"shadow\"}",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerIntrinsicWidth": "1",
                "framerAutoSizeImages": "true",
                "framerIntrinsicHeight": "32",
                "framerComponentViewportWidth": "true",
                "framerImmutableVariables": "true",
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./YZM3vWqiv.map
