// Generated by Framer (0f6ce29)
export default function metadata(params, activeLocale) {
    return {
        description: "Launch your design business in hours with this conversion-optimized portfolio template. Built with Framer's powerful CMS, it combines stunning project showcases with client management tools to help you land more clients and grow your business.",
        favicon: "https://framerusercontent.com/assets/Wg7q9IREdgstBg6HIJnpn11hY.svg",
        robots: "max-image-preview:large",
        socialImage: "https://framerusercontent.com/assets/sSaHokO18xSkbBHg2FtEE57HVU.png",
        title: "LaunchFolio Portfolio Framer Template"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}