// Generated by Framer (293632e)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    CycleVariantState,
    getFontsFromSharedStyle,
    RichText,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useOnVariantChange,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "/framerusercontent.com/modules/fmIcZLhhr1q0MfKcY4DO/hu8XDpNFKs1pXNBsgjPX/umXNQhy9r.js";
const cycleOrder = ["JJHa5mm3j", "DhYjSa2EJ", "MYVUm3Q25"];
const serializationHash = "framer-LR3rr";
const variantClassNames = {
    DhYjSa2EJ: "framer-v-u00ank",
    JJHa5mm3j: "framer-v-5gaglo",
    MYVUm3Q25: "framer-v-o4m0ea"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const xubQvRMln = undefined;
const itwgvvE_p = undefined;
const zXXdlfmkP = undefined;
const transition1 = {
    bounce: 0,
    delay: 0,
    duration: .8,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    "Text 1": "JJHa5mm3j",
    "Text 2": "DhYjSa2EJ",
    "Text 3": "MYVUm3Q25"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    text1,
    text2,
    text3,
    width,
    ...props
}) => {
    return { ...props,
        itwgvvE_p: text2 ? ? props.itwgvvE_p ? ? "build",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "JJHa5mm3j",
        xubQvRMln: text1 ? ? props.xubQvRMln ? ? "design",
        zXXdlfmkP: text3 ? ? props.zXXdlfmkP ? ? "create"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        xubQvRMln,
        itwgvvE_p,
        zXXdlfmkP,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "JJHa5mm3j",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onAppear1a2vbif = activeVariantCallback(async (...args) => {
        await delay(() => setVariant(CycleVariantState), 1500);
    });
    useOnVariantChange(baseVariant, {
        default: onAppear1a2vbif
    });
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-5gaglo", className, classNames),
                    "data-framer-name": "Text 1",
                    "data-highlight": true,
                    layoutDependency: layoutDependency,
                    layoutId: "JJHa5mm3j",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        DhYjSa2EJ: {
                            "data-framer-name": "Text 2"
                        },
                        MYVUm3Q25: {
                            "data-framer-name": "Text 3"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-1s8fn6c",
                                "data-styles-preset": "umXNQhy9r",
                                dir: "auto",
                                style: {
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255)))"
                                },
                                children: "design"
                            })
                        }),
                        className: "framer-1fw3mbg",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "Lo684096K",
                        style: {
                            "--extracted-r6o4lv": "var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                            filter: "blur(0px)",
                            opacity: 1,
                            WebkitFilter: "blur(0px)"
                        },
                        text: xubQvRMln,
                        variants: {
                            DhYjSa2EJ: {
                                filter: "blur(5px)",
                                opacity: 0,
                                WebkitFilter: "blur(5px)"
                            },
                            MYVUm3Q25: {
                                filter: "blur(5px)",
                                opacity: 0,
                                WebkitFilter: "blur(5px)"
                            }
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-1s8fn6c",
                                "data-styles-preset": "umXNQhy9r",
                                dir: "auto",
                                style: {
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255)))"
                                },
                                children: "build"
                            })
                        }),
                        className: "framer-1w6wwnn",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "xtdYBtZMe",
                        style: {
                            "--extracted-r6o4lv": "var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                            filter: "blur(5px)",
                            opacity: 0,
                            WebkitFilter: "blur(5px)"
                        },
                        text: itwgvvE_p,
                        variants: {
                            DhYjSa2EJ: {
                                filter: "blur(0px)",
                                opacity: 1,
                                WebkitFilter: "blur(0px)"
                            }
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-1s8fn6c",
                                "data-styles-preset": "umXNQhy9r",
                                dir: "auto",
                                style: {
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255)))"
                                },
                                children: "create"
                            })
                        }),
                        className: "framer-11hjb3k",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "gH6SSWiqO",
                        style: {
                            "--extracted-r6o4lv": "var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                            filter: "blur(5px)",
                            opacity: 0,
                            WebkitFilter: "blur(5px)"
                        },
                        text: zXXdlfmkP,
                        variants: {
                            MYVUm3Q25: {
                                filter: "blur(0px)",
                                opacity: 1,
                                WebkitFilter: "blur(0px)"
                            }
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-LR3rr.framer-xb2525, .framer-LR3rr .framer-xb2525 { display: block; }", ".framer-LR3rr.framer-5gaglo { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }", ".framer-LR3rr .framer-1fw3mbg { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-LR3rr .framer-1w6wwnn { bottom: -68px; flex: none; height: auto; left: 0px; position: absolute; white-space: pre; width: auto; z-index: 1; }", ".framer-LR3rr .framer-11hjb3k { flex: none; height: auto; left: 0px; position: absolute; top: -68px; white-space: pre; width: auto; z-index: 1; }", ".framer-LR3rr.framer-v-u00ank .framer-1fw3mbg { left: 0px; position: absolute; top: -68px; z-index: 1; }", ".framer-LR3rr.framer-v-u00ank .framer-1w6wwnn { bottom: unset; left: unset; position: relative; }", ".framer-LR3rr.framer-v-u00ank .framer-11hjb3k { bottom: -68px; top: unset; }", ".framer-LR3rr.framer-v-o4m0ea .framer-1fw3mbg { bottom: -68px; left: 0px; position: absolute; z-index: 1; }", ".framer-LR3rr.framer-v-o4m0ea .framer-1w6wwnn { bottom: unset; top: -68px; }", ".framer-LR3rr.framer-v-o4m0ea .framer-11hjb3k { left: unset; position: relative; top: unset; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 68
 * @framerIntrinsicWidth 209
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"DhYjSa2EJ":{"layout":["auto","auto"]},"MYVUm3Q25":{"layout":["auto","auto"]}}}
 * @framerVariables {"xubQvRMln":"text1","itwgvvE_p":"text2","zXXdlfmkP":"text3"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const Framero2Fu_SVVu = withCSS(Component, css, "framer-LR3rr");
export default Framero2Fu_SVVu;
Framero2Fu_SVVu.displayName = "Text Cycle";
Framero2Fu_SVVu.defaultProps = {
    height: 68,
    width: 209
};
addPropertyControls(Framero2Fu_SVVu, {
    variant: {
        options: ["JJHa5mm3j", "DhYjSa2EJ", "MYVUm3Q25"],
        optionTitles: ["Text 1", "Text 2", "Text 3"],
        title: "Variant",
        type: ControlType.Enum
    },
    xubQvRMln: {
        defaultValue: "design",
        displayTextArea: true,
        title: "Text 1",
        type: ControlType.String
    },
    itwgvvE_p: {
        defaultValue: "build",
        displayTextArea: true,
        title: "Text 2",
        type: ControlType.String
    },
    zXXdlfmkP: {
        defaultValue: "create",
        displayTextArea: true,
        title: "Text 3",
        type: ControlType.String
    }
});
addFonts(Framero2Fu_SVVu, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "/framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "/framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+1F00-1FFF",
        url: "/framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0370-03FF",
        url: "/framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "/framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "/framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "/framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "Framero2Fu_SVVu",
            "slots": [],
            "annotations": {
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "209",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"DhYjSa2EJ\":{\"layout\":[\"auto\",\"auto\"]},\"MYVUm3Q25\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerDisplayContentsDiv": "false",
                "framerAutoSizeImages": "true",
                "framerComponentViewportWidth": "true",
                "framerColorSyntax": "true",
                "framerContractVersion": "1",
                "framerIntrinsicHeight": "68",
                "framerVariables": "{\"xubQvRMln\":\"text1\",\"itwgvvE_p\":\"text2\",\"zXXdlfmkP\":\"text3\"}"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./o2Fu_SVVu.map
