// Generated by Framer (0951425)
import {
    addPropertyControls as e,
    ControlType as l,
    QueryEngine as t
} from "framer";
import {
    DatabaseCollection as a,
    DatabaseDictionaryIndex as r
} from "./WbwPHsjBi-0.js";
import {
    getRichTextJsonResolver as i
} from "./WbwPHsjBi-1.js";
let m = {
        A8q4fNlpa: {
            isNullable: !0,
            type: l.String
        },
        Aze0sg7i8: {
            isNullable: !0,
            type: l.Link
        },
        bKlfS_vZ3: {
            isNullable: !0,
            type: l.String
        },
        createdAt: {
            isNullable: !0,
            type: l.Date
        },
        CVzlyhpOy: {
            isNullable: !0,
            type: l.String
        },
        dfxBl8eYO: {
            isNullable: !0,
            type: l.String
        },
        eEsDVf9Yq: {
            isNullable: !0,
            type: l.Link
        },
        g4QbZPTtg: {
            definition: {
                isNullable: !0,
                type: l.String
            },
            isNullable: !0,
            type: l.Array
        },
        grpDTQWYm: {
            isNullable: !0,
            type: l.String
        },
        I2nvRUgKP: {
            isNullable: !0,
            type: l.String
        },
        i4BhDyLYh: {
            isNullable: !0,
            type: l.String
        },
        id: {
            isNullable: !1,
            type: l.String
        },
        JBV2mEd8S: {
            isNullable: !0,
            type: l.String
        },
        jdsTs2u1O: {
            isNullable: !0,
            type: l.Enum
        },
        JUxIVp_qv: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        KHf_dPMfz: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        L6phdRwGw: {
            isNullable: !0,
            type: l.Date
        },
        LQAuanKfK: {
            isNullable: !0,
            type: l.String
        },
        LxXW_VihP: {
            isNullable: !0,
            type: l.String
        },
        MvURTcnI6: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        N_egHjN2A: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        nextItemId: {
            isNullable: !0,
            type: l.String
        },
        NIJ4ovk23: {
            isNullable: !0,
            type: l.String
        },
        PaswN52lB: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        pHuE2iTw8: {
            isNullable: !0,
            type: l.Link
        },
        previousItemId: {
            isNullable: !0,
            type: l.String
        },
        qaAp9AEx5: {
            isNullable: !0,
            type: l.Number
        },
        qNx60GH3h: {
            isNullable: !0,
            type: l.String
        },
        qtp0G1Qva: {
            isNullable: !0,
            type: l.String
        },
        ROa67E_yS: {
            isNullable: !0,
            type: l.RichText
        },
        sc7eMxwxB: {
            isNullable: !0,
            type: l.Link
        },
        SRwfWRKdO: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        TfnX_T89B: {
            isNullable: !0,
            type: l.Number
        },
        updatedAt: {
            isNullable: !0,
            type: l.Date
        },
        UzhUb3GZt: {
            isNullable: !0,
            type: l.String
        },
        V1PIslv6l: {
            isNullable: !0,
            type: l.String
        },
        V33GrCta5: {
            isNullable: !0,
            type: l.String
        },
        vthCLYfzB: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        vufEjZADB: {
            isNullable: !0,
            type: l.String
        },
        xjEw2jMFz: {
            isNullable: !0,
            type: l.String
        },
        XJWCDUru2: {
            isNullable: !0,
            type: l.Link
        },
        xMUxHADTR: {
            isNullable: !0,
            type: l.String
        },
        Yc6ikGCcN: {
            isNullable: !0,
            type: l.String
        },
        yev0k0w6g: {
            isNullable: !0,
            type: l.String
        },
        YGnJ7skUP: {
            isNullable: !0,
            type: l.String
        }
    },
    o = ["id"],
    n = {
        type: 1
    },
    s = ["previousItemId"],
    c = ["nextItemId"],
    u = ["id", "dfxBl8eYO"],
    f = ["dfxBl8eYO", "id"],
    d = ["L6phdRwGw"],
    p = {
        type: 0
    },
    w = ["qNx60GH3h"],
    g = ["YGnJ7skUP"],
    y = ["xMUxHADTR"],
    h = ["pHuE2iTw8"],
    b = ["SRwfWRKdO"],
    N = ["KHf_dPMfz"],
    S = ["JBV2mEd8S"],
    x = ["A8q4fNlpa"],
    P = ["qaAp9AEx5"],
    B = ["yev0k0w6g"],
    R = ["TfnX_T89B"],
    L = ["vufEjZADB"],
    U = ["xjEw2jMFz"],
    j = ["ROa67E_yS"],
    H = ["CVzlyhpOy"],
    W = ["g4QbZPTtg"],
    v = ["jdsTs2u1O"],
    I = ["Aze0sg7i8"],
    V = ["eEsDVf9Yq"],
    T = ["XJWCDUru2"],
    A = ["sc7eMxwxB"],
    k = ["vthCLYfzB"],
    D = ["JUxIVp_qv"],
    C = ["MvURTcnI6"],
    O = ["PaswN52lB"],
    Y = ["N_egHjN2A"],
    z = ["I2nvRUgKP"],
    E = ["V33GrCta5"],
    q = ["grpDTQWYm"],
    G = ["i4BhDyLYh"],
    _ = ["V1PIslv6l"],
    K = ["LQAuanKfK"],
    M = ["bKlfS_vZ3"],
    J = ["UzhUb3GZt"],
    Q = ["LxXW_VihP"],
    Z = ["qtp0G1Qva"],
    F = ["Yc6ikGCcN"],
    X = ["NIJ4ovk23"],
    $ = ["dfxBl8eYO"],
    ee = [],
    el = e => {
        let l = ee[e];
        if (l) return l().then(e => e.default);
    },
    et = {},
    ea = i(et),
    er = new t,
    ei = {
        collectionByLocaleId: {
            default: new a({
                chunks: [new URL("./WbwPHsjBi-chunk-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")],
                id: "0f0792ed-e687-43f4-b53a-1a866fac5cb3default",
                indexes: [new r({
                    collation: n,
                    collectionSchema: m,
                    fieldNames: o,
                    range: {
                        from: 0,
                        to: 385
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: n,
                    collectionSchema: m,
                    fieldNames: s,
                    range: {
                        from: 385,
                        to: 769
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: n,
                    collectionSchema: m,
                    fieldNames: c,
                    range: {
                        from: 769,
                        to: 1149
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: n,
                    collectionSchema: m,
                    fieldNames: u,
                    range: {
                        from: 1149,
                        to: 1713
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: n,
                    collectionSchema: m,
                    fieldNames: f,
                    range: {
                        from: 1713,
                        to: 2277
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: d,
                    range: {
                        from: 2277,
                        to: 2594
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: w,
                    range: {
                        from: 2594,
                        to: 2939
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: g,
                    range: {
                        from: 2939,
                        to: 3817
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: y,
                    range: {
                        from: 3817,
                        to: 4209
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: h,
                    range: {
                        from: 4209,
                        to: 5259
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: b,
                    range: {
                        from: 5259,
                        to: 11754
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: N,
                    range: {
                        from: 11754,
                        to: 18684
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: S,
                    range: {
                        from: 18684,
                        to: 19007
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: x,
                    range: {
                        from: 19007,
                        to: 22102
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: P,
                    range: {
                        from: 22102,
                        to: 22419
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: B,
                    range: {
                        from: 22419,
                        to: 22719
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: R,
                    range: {
                        from: 22719,
                        to: 23036
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: L,
                    range: {
                        from: 23036,
                        to: 23327
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: U,
                    range: {
                        from: 23327,
                        to: 24707
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: j,
                    range: {
                        from: 24707,
                        to: 30488
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: H,
                    range: {
                        from: 30488,
                        to: 30893
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: W,
                    range: {
                        from: 30893,
                        to: 32100
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: v,
                    range: {
                        from: 32100,
                        to: 32492
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: I,
                    range: {
                        from: 32492,
                        to: 34399
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: V,
                    range: {
                        from: 34399,
                        to: 35452
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: T,
                    range: {
                        from: 35452,
                        to: 36487
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: A,
                    range: {
                        from: 36487,
                        to: 37523
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: k,
                    range: {
                        from: 37523,
                        to: 45536
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: D,
                    range: {
                        from: 45536,
                        to: 53628
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: C,
                    range: {
                        from: 53628,
                        to: 61751
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: O,
                    range: {
                        from: 61751,
                        to: 69948
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: Y,
                    range: {
                        from: 69948,
                        to: 76189
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: z,
                    range: {
                        from: 76189,
                        to: 76536
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: E,
                    range: {
                        from: 76536,
                        to: 76973
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: q,
                    range: {
                        from: 76973,
                        to: 77390
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: G,
                    range: {
                        from: 77390,
                        to: 77795
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: _,
                    range: {
                        from: 77795,
                        to: 78196
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: K,
                    range: {
                        from: 78196,
                        to: 78586
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: M,
                    range: {
                        from: 78586,
                        to: 78988
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: J,
                    range: {
                        from: 78988,
                        to: 79328
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: Q,
                    range: {
                        from: 79328,
                        to: 79624
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: Z,
                    range: {
                        from: 79624,
                        to: 79895
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: F,
                    range: {
                        from: 79895,
                        to: 80155
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: X,
                    range: {
                        from: 80155,
                        to: 80412
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: $,
                    range: {
                        from: 80412,
                        to: 80760
                    },
                    url: new URL("./WbwPHsjBi-indexes-default-0.framercms", "/framerusercontent.com/modules/VZpRON84AbRSSBe9URtw/E9ytJI6HxREJkjBZSotG/WbwPHsjBi.js").href.replace("/modules/", "/cms/")
                })],
                resolveRichText: ea,
                resolveVectorSetItem: el,
                schema: m
            })
        },
        displayName: "Templates",
        id: "0f0792ed-e687-43f4-b53a-1a866fac5cb3"
    };
export default ei;
e(ei, {
    L6phdRwGw: {
        title: "Date Added",
        type: l.Date
    },
    qNx60GH3h: {
        defaultValue: "",
        title: "Name",
        type: l.String
    },
    YGnJ7skUP: {
        defaultValue: "",
        title: "Byline",
        type: l.String
    },
    xMUxHADTR: {
        dataIdentifier: "local-module:collection/yL7DkRbUT:default",
        defaultValue: "q7L8hW_Wa",
        title: "Creator",
        type: l.CollectionReference
    },
    pHuE2iTw8: {
        title: "Preview Link",
        type: l.Link
    },
    SRwfWRKdO: {
        title: "Front page thumbnail",
        type: l.ResponsiveImage
    },
    KHf_dPMfz: {
        title: "Front page thumbnail 2",
        type: l.ResponsiveImage
    },
    JBV2mEd8S: {
        defaultValue: "",
        title: "Tags",
        type: l.String
    },
    A8q4fNlpa: {
        defaultValue: "",
        displayTextArea: !0,
        title: "Small Description",
        type: l.String
    },
    qaAp9AEx5: {
        defaultValue: 0,
        displayStepper: !1,
        max: 1e3,
        min: 0,
        title: "Standard Price",
        type: l.Number
    },
    yev0k0w6g: {
        defaultValue: "",
        title: "Standard Price String",
        type: l.String
    },
    TfnX_T89B: {
        defaultValue: 129,
        title: "Unlimited Price",
        type: l.Number
    },
    vufEjZADB: {
        defaultValue: "",
        title: "Unlimited Price String",
        type: l.String
    },
    xjEw2jMFz: {
        defaultValue: "",
        title: "Description Header",
        type: l.String
    },
    ROa67E_yS: {
        defaultValue: "",
        title: "Big Description",
        type: l.RichText
    },
    CVzlyhpOy: {
        defaultValue: "",
        title: "Main Category",
        type: l.String
    },
    g4QbZPTtg: {
        dataIdentifier: "local-module:collection/JEi6zbdxc:default",
        defaultValue: ["O6vGyC0X4"],
        title: "Template Categories",
        type: l.MultiCollectionReference
    },
    jdsTs2u1O: {
        defaultValue: "erFHzbA4D",
        options: ["erFHzbA4D", "aQvFTAnoU"],
        optionTitles: ["Polar", "Lemon Squeezy"],
        title: "Payment Platform",
        type: l.Enum
    },
    Aze0sg7i8: {
        title: "Store Checkout Link",
        type: l.Link
    },
    eEsDVf9Yq: {
        title: "Store Unlimited Checkout Link",
        type: l.Link
    },
    XJWCDUru2: {
        title: "BuyBtn Checkout Link",
        type: l.Link
    },
    sc7eMxwxB: {
        title: "BuyBtn Unlimited Checkout Link",
        type: l.Link
    },
    vthCLYfzB: {
        title: "Thumbnail 1",
        type: l.ResponsiveImage
    },
    JUxIVp_qv: {
        title: "Thumbnail 2",
        type: l.ResponsiveImage
    },
    MvURTcnI6: {
        title: "Thumbnail 3",
        type: l.ResponsiveImage
    },
    PaswN52lB: {
        title: "Thumbnail 4",
        type: l.ResponsiveImage
    },
    N_egHjN2A: {
        title: "Phone Image",
        type: l.ResponsiveImage
    },
    I2nvRUgKP: {
        defaultValue: "",
        title: "Page 1",
        type: l.String
    },
    V33GrCta5: {
        defaultValue: "",
        title: "Page 2",
        type: l.String
    },
    grpDTQWYm: {
        defaultValue: "",
        title: "Page 3",
        type: l.String
    },
    i4BhDyLYh: {
        defaultValue: "",
        title: "Page 4",
        type: l.String
    },
    V1PIslv6l: {
        defaultValue: "",
        title: "Page 5",
        type: l.String
    },
    LQAuanKfK: {
        defaultValue: "",
        title: "Page 6",
        type: l.String
    },
    bKlfS_vZ3: {
        defaultValue: "",
        title: "Page 7",
        type: l.String
    },
    UzhUb3GZt: {
        defaultValue: "",
        title: "Page 8",
        type: l.String
    },
    LxXW_VihP: {
        defaultValue: "",
        title: "Page 9",
        type: l.String
    },
    qtp0G1Qva: {
        defaultValue: "",
        title: "Page 10",
        type: l.String
    },
    Yc6ikGCcN: {
        defaultValue: "",
        title: "Page 11",
        type: l.String
    },
    NIJ4ovk23: {
        defaultValue: "",
        title: "Page 12",
        type: l.String
    },
    dfxBl8eYO: {
        preventLocalization: !1,
        title: "Slug",
        type: l.String
    },
    createdAt: {
        title: "Created",
        type: l.Date
    },
    updatedAt: {
        title: "Updated",
        type: l.Date
    },
    previousItemId: {
        dataIdentifier: "local-module:collection/WbwPHsjBi:default",
        title: "Previous",
        type: l.CollectionReference
    },
    nextItemId: {
        dataIdentifier: "local-module:collection/WbwPHsjBi:default",
        title: "Next",
        type: l.CollectionReference
    }
});
export const jdsTs2u1OToDisplayName = (e, l) => {
    switch (l ? .fallback, e) {
        case "erFHzbA4D":
            return "Polar";
        case "aQvFTAnoU":
            return "Lemon Squeezy";
        default:
            return "";
    }
};
export const enumToDisplayNameFunctions = {
    jdsTs2u1O: jdsTs2u1OToDisplayName
};
export const utils = {
    async getSlugByRecordId(e, l) {
        let [t] = await er.query({
            from: {
                data: ei,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "dfxBl8eYO",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "id",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l);
        return t ? .dfxBl8eYO;
    },
    async getRecordIdBySlug(e, l) {
        let [t] = await er.query({
            from: {
                data: ei,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "id",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "dfxBl8eYO",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l);
        return t ? .id;
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "data",
            "name": "data",
            "annotations": {
                "framerSlug": "dfxBl8eYO",
                "framerCollectionUtils": "1",
                "framerCollectionId": "WbwPHsjBi",
                "framerEnumToDisplayNameUtils": "2",
                "framerRecordIdKey": "id",
                "framerContractVersion": "1",
                "framerAutoSizeImages": "true",
                "framerColorSyntax": "false",
                "framerData": "true"
            }
        },
        "jdsTs2u1OToDisplayName": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "enumToDisplayNameFunctions": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "utils": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
