// Generated by Framer (293632e)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/2z1LAayU89TtN34qcAvL/WipFcG3Y6Git8QHrTVIe/xYEC_wF3E.js";
const cycleOrder = ["asFBFV0EA", "fEo6BVDN9"];
const serializationHash = "framer-H4iC6";
const variantClassNames = {
    asFBFV0EA: "framer-v-wkg5xb",
    fEo6BVDN9: "framer-v-px5sp4"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const BXqokVo6Z = undefined;
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    Dark: "fEo6BVDN9",
    White: "asFBFV0EA"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    title,
    width,
    ...props
}) => {
    return { ...props,
        BXqokVo6Z: title ? ? props.BXqokVo6Z ? ? "Pause or cancel anytime",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "asFBFV0EA"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        BXqokVo6Z,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "asFBFV0EA",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-wkg5xb", className, classNames),
                    "data-border": true,
                    "data-framer-name": "White",
                    layoutDependency: layoutDependency,
                    layoutId: "asFBFV0EA",
                    ref: refBinding,
                    style: {
                        "--border-bottom-width": "1px",
                        "--border-color": "var(--token-08cb0f10-6dc5-4949-913f-dbd7168f1cf0, rgb(240, 240, 240))",
                        "--border-left-width": "1px",
                        "--border-right-width": "1px",
                        "--border-style": "solid",
                        "--border-top-width": "1px",
                        backdropFilter: "blur(5px)",
                        backgroundColor: "rgb(255, 255, 255)",
                        borderBottomLeftRadius: 24,
                        borderBottomRightRadius: 24,
                        borderTopLeftRadius: 24,
                        borderTopRightRadius: 24,
                        boxShadow: "0px 0.6021873017743928px 0.6021873017743928px -1.25px rgba(0, 0, 0, 0.18), 0px 2.288533303243457px 2.288533303243457px -2.5px rgba(0, 0, 0, 0.16), 0px 10px 10px -3.75px rgba(0, 0, 0, 0.06)",
                        WebkitBackdropFilter: "blur(5px)",
                        ...style
                    },
                    variants: {
                        fEo6BVDN9: {
                            "--border-color": "var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
                            backgroundColor: "var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
                            boxShadow: "inset 0px 2px 4px 0px rgba(255, 255, 255, 0.4), 0px 0.7409732186279143px 0.7409732186279143px -0.75px rgba(0, 0, 0, 0.33), 0px 2.0178668455264415px 2.0178668455264415px -1.5px rgba(0, 0, 0, 0.32), 0px 4.430505261661892px 4.430505261661892px -2.25px rgba(0, 0, 0, 0.3), 0px 9.834710084098335px 9.834710084098335px -3px rgba(0, 0, 0, 0.25), 0px 25px 25px -3.75px rgba(0, 0, 0, 0.11), 0px 0px 0px 1px var(--token-46244ad7-86a7-41b8-b44b-214d95b54c13, rgb(130, 130, 130))"
                        }
                    },
                    ...addPropertyOverrides({
                        fEo6BVDN9: {
                            "data-framer-name": "Dark"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-455vy9",
                                "data-styles-preset": "xYEC_wF3E",
                                dir: "auto",
                                children: "Pause or cancel anytime"
                            })
                        }),
                        className: "framer-1xukypq",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "jgHeT4Q69",
                        style: {
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                            "--framer-paragraph-spacing": "0px"
                        },
                        text: BXqokVo6Z,
                        variants: {
                            fEo6BVDN9: {
                                "--extracted-r6o4lv": "var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255))"
                            }
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            fEo6BVDN9: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        className: "framer-styles-preset-455vy9",
                                        "data-styles-preset": "xYEC_wF3E",
                                        dir: "auto",
                                        style: {
                                            "--framer-text-color": "var(--extracted-r6o4lv, var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255)))"
                                        },
                                        children: "Pause or cancel anytime"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-H4iC6.framer-z2n1g, .framer-H4iC6 .framer-z2n1g { display: block; }", ".framer-H4iC6.framer-wkg5xb { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: 30px; justify-content: center; overflow: visible; padding: 12px; position: relative; width: min-content; }", ".framer-H4iC6 .framer-1xukypq { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ...sharedStyle.css, '.framer-H4iC6[data-border="true"]::after, .framer-H4iC6 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 30
 * @framerIntrinsicWidth 159
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","fixed"]},"fEo6BVDN9":{"layout":["auto","fixed"]}}}
 * @framerVariables {"BXqokVo6Z":"title"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const Framerz7PecXLcf = withCSS(Component, css, "framer-H4iC6");
export default Framerz7PecXLcf;
Framerz7PecXLcf.displayName = "Label";
Framerz7PecXLcf.defaultProps = {
    height: 30,
    width: 159
};
addPropertyControls(Framerz7PecXLcf, {
    variant: {
        options: ["asFBFV0EA", "fEo6BVDN9"],
        optionTitles: ["White", "Dark"],
        title: "Variant",
        type: ControlType.Enum
    },
    BXqokVo6Z: {
        defaultValue: "Pause or cancel anytime",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    }
});
addFonts(Framerz7PecXLcf, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Framerz7PecXLcf",
            "slots": [],
            "annotations": {
                "framerVariables": "{\"BXqokVo6Z\":\"title\"}",
                "framerImmutableVariables": "true",
                "framerContractVersion": "1",
                "framerIntrinsicWidth": "159",
                "framerColorSyntax": "true",
                "framerAutoSizeImages": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"fixed\"]},\"fEo6BVDN9\":{\"layout\":[\"auto\",\"fixed\"]}}}",
                "framerIntrinsicHeight": "30",
                "framerComponentViewportWidth": "true",
                "framerDisplayContentsDiv": "false"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./z7PecXLcf.map