// Generated by Framer (f21d278)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    SVG,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const cycleOrder = ["LAzaFDLEP", "LVxmklpu4"];
const serializationHash = "framer-OtBkq";
const variantClassNames = {
    LAzaFDLEP: "framer-v-1ye5gzy",
    LVxmklpu4: "framer-v-mkwthb"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    Default: "LAzaFDLEP",
    White: "LVxmklpu4"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "LAzaFDLEP"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "LAzaFDLEP",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1ye5gzy", className, classNames),
                    "data-framer-name": "Default",
                    layoutDependency: layoutDependency,
                    layoutId: "LAzaFDLEP",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        LVxmklpu4: {
                            "data-framer-name": "White"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsxs(SVG, {
                        className: "framer-1rx7maj",
                        layoutDependency: layoutDependency,
                        layoutId: "ZIeC6W_ej",
                        requiresOverflowVisible: false,
                        svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 16 16" overflow="visible"><path d="M 12.8 0 C 14.567 0 16 1.433 16 3.2 L 16 12.8 C 16 14.567 14.567 16 12.8 16 L 3.2 16 C 1.433 16 0 14.567 0 12.8 L 0 3.2 C 0 1.433 1.433 0 3.2 0 Z M 4.4 6.2 L 8.386 6.2 L 3.693 10.893 L 5.108 12.307 L 9.8 7.614 L 9.8 11.6 L 11.8 11.6 L 11.8 5.2 C 11.8 4.648 11.352 4.2 10.8 4.2 L 4.4 4.2 Z" fill="var(--token-a76a7bdc-12ae-45c2-b714-05c440884cc5, rgb(237, 70, 9))"></path></svg>',
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            LVxmklpu4: {
                                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 16 16" overflow="visible"><path d="M 12.8 0 C 14.567 0 16 1.433 16 3.2 L 16 12.8 C 16 14.567 14.567 16 12.8 16 L 3.2 16 C 1.433 16 0 14.567 0 12.8 L 0 3.2 C 0 1.433 1.433 0 3.2 0 Z M 4.4 6.2 L 8.386 6.2 L 3.693 10.893 L 5.108 12.307 L 9.8 7.614 L 9.8 11.6 L 11.8 11.6 L 11.8 5.2 C 11.8 4.648 11.352 4.2 10.8 4.2 L 4.4 4.2 Z" fill="rgb(255, 255, 255)"></path></svg>'
                            }
                        }, baseVariant, gestureVariant),
                        children: [ /*#__PURE__*/ _jsx(SVG, {
                            className: "framer-tfjy4m",
                            layoutDependency: layoutDependency,
                            layoutId: "jGkeZNrHa",
                            requiresOverflowVisible: false,
                            svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 16 16" overflow="visible"><path d="M 3.2 0 C 1.433 0 0 1.433 0 3.2 L 0 12.8 C 0 14.567 1.433 16 3.2 16 L 12.8 16 C 14.567 16 16 14.567 16 12.8 L 16 3.2 C 16 1.433 14.567 0 12.8 0 Z" fill="transparent"></path></svg>',
                            withExternalLayout: true
                        }), /*#__PURE__*/ _jsx(SVG, {
                            className: "framer-chb7n8",
                            layoutDependency: layoutDependency,
                            layoutId: "ByF3HaiIj",
                            requiresOverflowVisible: false,
                            svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 8.107 8.107" overflow="visible"><path d="M 0.707 2 L 4.692 2 L 0 6.693 L 1.414 8.107 L 6.107 3.414 L 6.107 7.4 L 8.107 7.4 L 8.107 1 C 8.107 0.448 7.659 0 7.107 0 L 0.707 0 Z" fill="transparent"></path></svg>',
                            withExternalLayout: true
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-OtBkq.framer-1lc3aas, .framer-OtBkq .framer-1lc3aas { display: block; }", ".framer-OtBkq.framer-1ye5gzy { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }", ".framer-OtBkq .framer-1rx7maj { height: 16px; position: relative; width: 16px; }", ".framer-OtBkq .framer-tfjy4m { height: 16px; left: 0px; position: absolute; top: 0px; width: 16px; }", ".framer-OtBkq .framer-chb7n8 { height: 8px; left: 4px; position: absolute; top: 4px; width: 8px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 16
 * @framerIntrinsicWidth 16
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"LVxmklpu4":{"layout":["auto","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerZTEGydyFL = withCSS(Component, css, "framer-OtBkq");
export default FramerZTEGydyFL;
FramerZTEGydyFL.displayName = "Small Logo";
FramerZTEGydyFL.defaultProps = {
    height: 16,
    width: 16
};
addPropertyControls(FramerZTEGydyFL, {
    variant: {
        options: ["LAzaFDLEP", "LVxmklpu4"],
        optionTitles: ["Default", "White"],
        title: "Variant",
        type: ControlType.Enum
    }
});
addFonts(FramerZTEGydyFL, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerZTEGydyFL",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicWidth": "16",
                "framerComponentViewportWidth": "true",
                "framerColorSyntax": "true",
                "framerAutoSizeImages": "true",
                "framerImmutableVariables": "true",
                "framerIntrinsicHeight": "16",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"LVxmklpu4\":{\"layout\":[\"auto\",\"auto\"]}}}"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./ZTEGydyFL.map