// Generated by Framer (293632e)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    ComponentViewportProvider,
    cx,
    forwardLoader,
    getFonts,
    getFontsFromSharedStyle,
    Link,
    RichText,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle2 from "/framerusercontent.com/modules/15o7bKlbnBDp2TQCFSZ2/ctCfN89KVvVVqogr3Mks/aAdohScXF.js";
import * as sharedStyle from "/framerusercontent.com/modules/4yeHosl6igbAWcnv76JG/oMRw17hjQww3rpVlI9OZ/fdldKf5t1.js";
import * as sharedStyle1 from "/framerusercontent.com/modules/2z1LAayU89TtN34qcAvL/WipFcG3Y6Git8QHrTVIe/xYEC_wF3E.js";
import ProfilePicture from "/framerusercontent.com/modules/1IJXf6JFFS6wQwUEEt8E/90r2Wi5ZuiHb8eaVnzyS/QHsZGkb1s.js";
const ProfilePictureFonts = getFonts(ProfilePicture);
const serializationHash = "framer-nejD3";
const variantClassNames = {
    hOuImOpGI: "framer-v-2lau7k"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "hOuImOpGI",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className, sharedStyle2.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-2lau7k", className, classNames),
                    "data-framer-name": "Variant 1",
                    layoutDependency: layoutDependency,
                    layoutId: "hOuImOpGI",
                    ref: refBinding,
                    style: { ...style
                    },
                    children: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 64,
                        width: "38px",
                        y: (componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 200) - 0 - 64) / 2),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-5wjjx5-container",
                            layoutDependency: layoutDependency,
                            layoutId: "VmDQUCkP6-container",
                            nodeId: "VmDQUCkP6",
                            rendersWithMotion: true,
                            scopeId: "rKNwAsolT",
                            children: /*#__PURE__*/ _jsx(ProfilePicture, {
                                height: "100%",
                                id: "VmDQUCkP6",
                                layoutId: "VmDQUCkP6",
                                style: {
                                    height: "100%",
                                    width: "100%"
                                },
                                width: "100%"
                            })
                        })
                    }), /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-19u0y2y",
                        "data-framer-name": "Name / Email",
                        layoutDependency: layoutDependency,
                        layoutId: "H4DetnE7B",
                        children: [ /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-3j1c0u",
                                    "data-styles-preset": "fdldKf5t1",
                                    dir: "auto",
                                    children: "ATOMIC MEDIA"
                                })
                            }),
                            className: "framer-1wpem65",
                            "data-framer-name": "Name",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "eqlhbAKGo",
                            style: {
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline"
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-455vy9",
                                    "data-styles-preset": "xYEC_wF3E",
                                    dir: "auto",
                                    style: {
                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--token-994646e0-68ea-49d7-897a-104048558f6f, rgb(84, 84, 84)))"
                                    },
                                    children: /*#__PURE__*/ _jsx(Link, {
                                        href: "mailto:info@atomicmedia.in",
                                        motionChild: true,
                                        nodeId: "PrJCLea1Y",
                                        openInNewTab: true,
                                        relValues: [],
                                        scopeId: "rKNwAsolT",
                                        smoothScroll: false,
                                        children: /*#__PURE__*/ _jsx(motion.a, {
                                            className: "framer-styles-preset-1pmp3vy",
                                            "data-styles-preset": "aAdohScXF",
                                            children: "info@atomicmedia.in"
                                        })
                                    })
                                })
                            }),
                            className: "framer-8x11cq",
                            "data-framer-name": "Email",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "PrJCLea1Y",
                            style: {
                                "--extracted-r6o4lv": "var(--token-994646e0-68ea-49d7-897a-104048558f6f, rgb(84, 84, 84))"
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })]
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-nejD3.framer-10zfjoq, .framer-nejD3 .framer-10zfjoq { display: block; }", ".framer-nejD3.framer-2lau7k { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 416px; }", ".framer-nejD3 .framer-5wjjx5-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 64px); position: relative; width: 38px; }", ".framer-nejD3 .framer-19u0y2y { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }", ".framer-nejD3 .framer-1wpem65, .framer-nejD3 .framer-8x11cq { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ...sharedStyle.css, ...sharedStyle1.css, ...sharedStyle2.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 38
 * @framerIntrinsicWidth 416
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerrKNwAsolT = withCSS(Component, css, "framer-nejD3");
export default FramerrKNwAsolT;
FramerrKNwAsolT.displayName = "Your Details";
FramerrKNwAsolT.defaultProps = {
    height: 38,
    width: 416
};
addFonts(FramerrKNwAsolT, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "/framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "/framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+1F00-1FFF",
        url: "/framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0370-03FF",
        url: "/framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "/framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "/framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "/framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...ProfilePictureFonts, ...getFontsFromSharedStyle(sharedStyle.fonts), ...getFontsFromSharedStyle(sharedStyle1.fonts), ...getFontsFromSharedStyle(sharedStyle2.fonts)], {
    supportsExplicitInterCodegen: true
});
FramerrKNwAsolT.loader = {
    load: (props, context) => {
        const locale = context.locale;
        return Promise.allSettled([forwardLoader(ProfilePicture, {}, context)]);
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerrKNwAsolT",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "416",
                "framerAutoSizeImages": "true",
                "framerColorSyntax": "true",
                "framerImmutableVariables": "true",
                "framerIntrinsicHeight": "38",
                "framerContractVersion": "1",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerDisplayContentsDiv": "false",
                "framerComponentViewportWidth": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
