// Generated by Framer (7e4cc89)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useOnVariantChange,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const cycleOrder = ["grFRFgHIy", "W9iGAwtzE", "Y6ZFa8Zp9", "WldtEnp20", "eNQC3xoax"];
const serializationHash = "framer-HkMLt";
const variantClassNames = {
    eNQC3xoax: "framer-v-1k0ocwq",
    grFRFgHIy: "framer-v-1ioohxk",
    W9iGAwtzE: "framer-v-jrtodj",
    WldtEnp20: "framer-v-hgsvya",
    Y6ZFa8Zp9: "framer-v-ptwsiq"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: 0,
    delay: 0,
    duration: .6,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Dot 1": "W9iGAwtzE",
    "Dot 2": "Y6ZFa8Zp9",
    "Dot 3": "WldtEnp20",
    Default: "grFRFgHIy",
    X: "eNQC3xoax"
};
const getProps = ({
    height,
    id,
    mouseClick,
    mouseEnter,
    width,
    ...props
}) => {
    return { ...props,
        FtoTLHMJY: mouseEnter ? ? props.FtoTLHMJY,
        mQfSgck7Q: mouseClick ? ? props.mQfSgck7Q,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "grFRFgHIy"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        FtoTLHMJY,
        mQfSgck7Q,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "grFRFgHIy",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTap13csbq = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (mQfSgck7Q) {
            const res = await mQfSgck7Q(...args);
            if (res === false) return false;
        }
    });
    const onAppearj8vb70 = activeVariantCallback(async (...args) => {
        await delay(() => setVariant("W9iGAwtzE"), 400);
    });
    const onMouseEntercv2029 = activeVariantCallback(async (...args) => {
        setGestureState({
            isHovered: true
        });
        if (FtoTLHMJY) {
            const res = await FtoTLHMJY(...args);
            if (res === false) return false;
        }
    });
    const onAppear1nvrn54 = activeVariantCallback(async (...args) => {
        await delay(() => setVariant("Y6ZFa8Zp9"), 400);
    });
    const onAppearw9gqou = activeVariantCallback(async (...args) => {
        await delay(() => setVariant("WldtEnp20"), 400);
    });
    const onAppear45kyeh = activeVariantCallback(async (...args) => {
        await delay(() => setVariant("grFRFgHIy"), 400);
    });
    useOnVariantChange(baseVariant, {
        default: onAppearj8vb70,
        eNQC3xoax: undefined,
        W9iGAwtzE: onAppear1nvrn54,
        WldtEnp20: onAppear45kyeh,
        Y6ZFa8Zp9: onAppearw9gqou
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1ioohxk", className, classNames),
                    "data-framer-name": "Default",
                    "data-highlight": true,
                    layoutDependency: layoutDependency,
                    layoutId: "grFRFgHIy",
                    onMouseEnter: onMouseEntercv2029,
                    onTap: onTap13csbq,
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        eNQC3xoax: {
                            "data-framer-name": "X"
                        },
                        W9iGAwtzE: {
                            "data-framer-name": "Dot 1"
                        },
                        WldtEnp20: {
                            "data-framer-name": "Dot 3"
                        },
                        Y6ZFa8Zp9: {
                            "data-framer-name": "Dot 2"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-b0xt18",
                        "data-framer-name": "dot 1",
                        layoutDependency: layoutDependency,
                        layoutId: "nDNIG_8o5",
                        style: {
                            backgroundColor: "var(--token-46244ad7-86a7-41b8-b44b-214d95b54c13, rgb(130, 130, 130))",
                            borderBottomLeftRadius: 24,
                            borderBottomRightRadius: 24,
                            borderTopLeftRadius: 24,
                            borderTopRightRadius: 24,
                            rotate: 0
                        },
                        variants: {
                            eNQC3xoax: {
                                backgroundColor: "var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
                                rotate: -45
                            },
                            W9iGAwtzE: {
                                backgroundColor: "var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))"
                            }
                        }
                    }), /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1oavwup",
                        "data-framer-name": "dot 2",
                        layoutDependency: layoutDependency,
                        layoutId: "tOPpTnzHi",
                        style: {
                            backgroundColor: "var(--token-46244ad7-86a7-41b8-b44b-214d95b54c13, rgb(130, 130, 130))",
                            borderBottomLeftRadius: 24,
                            borderBottomRightRadius: 24,
                            borderTopLeftRadius: 24,
                            borderTopRightRadius: 24,
                            opacity: 1
                        },
                        variants: {
                            eNQC3xoax: {
                                opacity: 0
                            },
                            Y6ZFa8Zp9: {
                                backgroundColor: "var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))"
                            }
                        }
                    }), /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-ks4rgq",
                        "data-framer-name": "dot 3",
                        layoutDependency: layoutDependency,
                        layoutId: "IUMmD13g3",
                        style: {
                            backgroundColor: "var(--token-46244ad7-86a7-41b8-b44b-214d95b54c13, rgb(130, 130, 130))",
                            borderBottomLeftRadius: 24,
                            borderBottomRightRadius: 24,
                            borderTopLeftRadius: 24,
                            borderTopRightRadius: 24,
                            rotate: 0
                        },
                        variants: {
                            eNQC3xoax: {
                                backgroundColor: "var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
                                rotate: 45
                            },
                            WldtEnp20: {
                                backgroundColor: "var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))"
                            }
                        }
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-HkMLt.framer-2zcc2e, .framer-HkMLt .framer-2zcc2e { display: block; }", ".framer-HkMLt.framer-1ioohxk { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: 24px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 24px; }", ".framer-HkMLt .framer-b0xt18 { flex: none; height: 6px; left: calc(12.500000000000021% - 6px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 6px / 2); width: 6px; z-index: 1; }", ".framer-HkMLt .framer-1oavwup { flex: none; height: 6px; left: calc(50.00000000000002% - 6px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 6px / 2); width: 6px; z-index: 1; }", ".framer-HkMLt .framer-ks4rgq { flex: none; height: 6px; left: calc(87.50000000000003% - 6px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 6px / 2); width: 6px; z-index: 1; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-HkMLt.framer-1ioohxk { gap: 0px; } .framer-HkMLt.framer-1ioohxk > * { margin: 0px; margin-left: calc(4px / 2); margin-right: calc(4px / 2); } .framer-HkMLt.framer-1ioohxk > :first-child { margin-left: 0px; } .framer-HkMLt.framer-1ioohxk > :last-child { margin-right: 0px; } }", ".framer-HkMLt.framer-v-jrtodj .framer-b0xt18, .framer-HkMLt.framer-v-ptwsiq .framer-1oavwup, .framer-HkMLt.framer-v-hgsvya .framer-ks4rgq { top: calc(37.50000000000002% - 6px / 2); }", ".framer-HkMLt.framer-v-1k0ocwq .framer-b0xt18, .framer-HkMLt.framer-v-1k0ocwq .framer-ks4rgq { height: 20px; left: calc(50.00000000000002% - 2px / 2); top: calc(50.00000000000002% - 20px / 2); width: 2px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 24
 * @framerIntrinsicWidth 24
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"W9iGAwtzE":{"layout":["fixed","fixed"]},"Y6ZFa8Zp9":{"layout":["fixed","fixed"]},"WldtEnp20":{"layout":["fixed","fixed"]},"eNQC3xoax":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"FtoTLHMJY":"mouseEnter","mQfSgck7Q":"mouseClick"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerHlovKhNxl = withCSS(Component, css, "framer-HkMLt");
export default FramerHlovKhNxl;
FramerHlovKhNxl.displayName = "Dots";
FramerHlovKhNxl.defaultProps = {
    height: 24,
    width: 24
};
addPropertyControls(FramerHlovKhNxl, {
    variant: {
        options: ["grFRFgHIy", "W9iGAwtzE", "Y6ZFa8Zp9", "WldtEnp20", "eNQC3xoax"],
        optionTitles: ["Default", "Dot 1", "Dot 2", "Dot 3", "X"],
        title: "Variant",
        type: ControlType.Enum
    },
    FtoTLHMJY: {
        title: "Mouse Enter",
        type: ControlType.EventHandler
    },
    mQfSgck7Q: {
        title: "Mouse Click",
        type: ControlType.EventHandler
    }
});
addFonts(FramerHlovKhNxl, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerHlovKhNxl",
            "slots": [],
            "annotations": {
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicWidth": "24",
                "framerIntrinsicHeight": "24",
                "framerImmutableVariables": "true",
                "framerContractVersion": "1",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"W9iGAwtzE\":{\"layout\":[\"fixed\",\"fixed\"]},\"Y6ZFa8Zp9\":{\"layout\":[\"fixed\",\"fixed\"]},\"WldtEnp20\":{\"layout\":[\"fixed\",\"fixed\"]},\"eNQC3xoax\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerVariables": "{\"FtoTLHMJY\":\"mouseEnter\",\"mQfSgck7Q\":\"mouseClick\"}",
                "framerComponentViewportWidth": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./HlovKhNxl.map