// Generated by Framer (1a93ff7)
import siteMetadata from "#framer/local/siteMetadata/siteMetadata/siteMetadata.js";
export default function metadata(params, activeLocale) {
    return {
        breakpoints: [{
            hash: "72rtr7",
            mediaQuery: "(min-width: 1200px)"
        }, {
            hash: "dsxqep",
            mediaQuery: "(min-width: 992px) and (max-width: 1199.98px)"
        }, {
            hash: "1d7c730",
            mediaQuery: "(min-width: 768px) and (max-width: 991.98px)"
        }, {
            hash: "1slso0x",
            mediaQuery: "(max-width: 767.98px)"
        }],
        description: siteMetadata(params, activeLocale).description,
        elements: {
            bPRlM5v_3: "projects",
            BZchDvhMe: "hero",
            O1EWxm2cI: "services",
            V8zY16Byd: "topprojects",
            wa1OpPtbn: "main-1",
            wWxpymqOt: "faq",
            ymGWWWUM9: "pricing"
        },
        framerSearch: {
            index: true
        },
        robots: "max-image-preview:large",
        serializationId: "framer-rD7YC",
        title: siteMetadata(params, activeLocale).title || "Home",
        viewport: "width=device-width"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}