// Generated by Framer (6ca5d98)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    useSVGTemplate,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const mask = "var(--framer-icon-mask)";
const Base = /*#__PURE__*/ forwardRef(function(props, ref) {
    return /*#__PURE__*/ _jsx("svg", { ...props,
        ref: ref,
        children: props.children
    });
});
const MotionSVG = motion.create(Base);
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(MotionSVG, { ...rest,
        layoutId: layoutId,
        ref: ref,
        children: children
    }) : /*#__PURE__*/ _jsx("svg", { ...rest,
        ref: ref,
        children: children
    });
});
const svg = '<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 11.25 L 0 1.5 C 0 0.672 0.672 0 1.5 0 L 15 0 C 15.828 0 16.5 0.672 16.5 1.5 L 16.5 11.25 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="11.25px" id="WfV7WBXdz" transform="translate(3.75 5.25)" width="16.5px"/><path d="M 0 11.25 L 0 1.5 C 0 0.672 0.672 0 1.5 0 L 15 0 C 15.828 0 16.5 0.672 16.5 1.5 L 16.5 11.25" fill="transparent" height="11.25px" id="KBgEezkCN" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(3.75 5.25)" width="16.5px"/><path d="M 0 0 L 19.5 0 L 19.5 0 L 19.5 1.5 C 19.5 2.328 18.828 3 18 3 L 1.5 3 C 0.672 3 0 2.328 0 1.5 L 0 0 Z" fill="transparent" height="3px" id="Ti9CTjmHy" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(2.25 16.5)" width="19.5px"/><path d="M 3 0 L 0 0" fill="transparent" height="1px" id="MHqbROsB8" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(10.5 8.25)" width="3px"/></svg>';
const getProps = ({
    alpha,
    color,
    height,
    id,
    width,
    width1,
    ...props
}) => {
    return { ...props,
        ezTt3ayMo: color ? ? props.ezTt3ayMo ? ? "rgb(0, 0, 0)",
        lschgej4H: width1 ? ? props.lschgej4H ? ? 1.5,
        qxTvv_EBh: alpha ? ? props.qxTvv_EBh
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        ezTt3ayMo,
        lschgej4H,
        qxTvv_EBh,
        ...restProps
    } = getProps(props);
    const href = useSVGTemplate("1874634908", svg);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-ULIMo", className),
        layoutId: layoutId,
        ref: ref,
        role: "presentation",
        style: {
            "--1m6trwb": qxTvv_EBh,
            "--21h8s6": ezTt3ayMo,
            "--pgex8v": lschgej4H,
            ...style
        },
        viewBox: "0 0 24 24",
        children: /*#__PURE__*/ _jsx("use", {
            href: href
        })
    });
});
const css = [`.framer-ULIMo { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"ezTt3ayMo":"color","lschgej4H":"width1","qxTvv_EBh":"alpha"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Laptop","color":{"type":"variable","value":"21h8s6"},"set":{"localId":"vectorSet/NGVKdicsm","id":"NGVKdicsm","moduleId":"omX0gWFPqDwhaiWwf6ab"}}
 * @framerDisableUnlink true
 */
const Icon = withCSS(Component, css, "framer-ULIMo");
Icon.displayName = "Laptop";
export default Icon;
addPropertyControls(Icon, {
    ezTt3ayMo: {
        defaultValue: "rgb(0, 0, 0)",
        hidden: false,
        title: "Color",
        type: ControlType.Color
    },
    lschgej4H: {
        defaultValue: 1.5,
        displayStepper: true,
        hidden: false,
        max: 6,
        min: 0,
        step: .5,
        title: "Width",
        type: ControlType.Number
    },
    qxTvv_EBh: {
        defaultValue: 0,
        displayStepper: true,
        hidden: false,
        max: 1,
        min: 0,
        step: .1,
        title: "Alpha",
        type: ControlType.Number
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "24",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerIntrinsicHeight": "24",
                "framerContractVersion": "1",
                "framerVariables": "{\"ezTt3ayMo\":\"color\",\"lschgej4H\":\"width1\",\"qxTvv_EBh\":\"alpha\"}",
                "framerDisableUnlink": "true",
                "framerImmutableVariables": "true",
                "framerVector": "{\"name\":\"Laptop\",\"color\":{\"type\":\"variable\",\"value\":\"21h8s6\"},\"set\":{\"localId\":\"vectorSet/NGVKdicsm\",\"id\":\"NGVKdicsm\",\"moduleId\":\"omX0gWFPqDwhaiWwf6ab\"}}",
                "framerSupportedLayoutHeight": "any-prefer-fixed"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}