// Generated by Framer (27b79d7)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    useSVGTemplate,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const qfBdYY45Z = undefined;
const DfxTrNMpt = undefined;
const mask = "var(--framer-icon-mask)";
const Base = /*#__PURE__*/ forwardRef(function(props, ref) {
    return /*#__PURE__*/ _jsx("svg", { ...props,
        ref: ref,
        children: props.children
    });
});
const MotionSVG = motion.create(Base);
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(MotionSVG, { ...rest,
        layoutId: layoutId,
        ref: ref,
        children: children
    }) : /*#__PURE__*/ _jsx("svg", { ...rest,
        ref: ref,
        children: children
    });
});
const svg = '<svg display="block" role="presentation" viewBox="0 0 19 20" xmlns="http://www.w3.org/2000/svg"><g d="M 15.755 15.755 C 17 14.51 17 12.508 17 8.5 C 17 4.493 17 2.489 15.755 1.245 C 14.51 0 12.508 0 8.5 0 C 4.493 0 2.489 0 1.245 1.245 C 0 2.489 0 4.492 0 8.5 C 0 12.507 0 14.511 1.245 15.755 C 2.489 17 4.492 17 8.5 17 C 12.507 17 14.511 17 15.755 15.755 Z M 17 5.816 L 0 5.816 M 12.079 17 L 12.079 5.816" fill="transparent" height="17.000000250966927px" id="EsEmlSOHK" transform="translate(1 2)" width="17px"><path d="M 15.755 15.755 C 17 14.51 17 12.508 17 8.5 C 17 4.493 17 2.489 15.755 1.245 C 14.51 0 12.508 0 8.5 0 C 4.493 0 2.489 0 1.245 1.245 C 0 2.489 0 4.492 0 8.5 C 0 12.507 0 14.511 1.245 15.755 C 2.489 17 4.492 17 8.5 17 C 12.507 17 14.511 17 15.755 15.755 Z" fill="transparent" height="17px" id="vQi3vucjL" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--q88lbe, 1.5)" stroke="var(--pxuiy5, var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(0, 0, 0)))" width="17px"/><path d="M 17 0 L 0 0 M 12.079 11.184 L 12.079 0" fill="transparent" height="11.184210551412482px" id="AKuRljAQY" stroke-dasharray="" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-width="var(--q88lbe, 1.5)" stroke="var(--pxuiy5, var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(0, 0, 0)))" transform="translate(0 5.816)" width="17px"/></g></svg>';
const getProps = ({
    color,
    height,
    id,
    strokeWidth,
    width,
    ...props
}) => {
    return { ...props,
        DfxTrNMpt: color ? ? props.DfxTrNMpt ? ? "var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(0, 0, 0))",
        qfBdYY45Z: strokeWidth ? ? props.qfBdYY45Z ? ? 1.5
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        DfxTrNMpt,
        qfBdYY45Z,
        ...restProps
    } = getProps(props);
    const href = useSVGTemplate("153675083", svg);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-1kqO8", className),
        layoutId: layoutId,
        ref: ref,
        role: "presentation",
        style: {
            "--pxuiy5": DfxTrNMpt,
            "--q88lbe": qfBdYY45Z,
            ...style
        },
        viewBox: "0 0 19 20",
        children: /*#__PURE__*/ _jsx("use", {
            href: href
        })
    });
});
const css = [`.framer-1kqO8 { -webkit-mask: ${mask}; aspect-ratio: 0.95; display: block; mask: ${mask}; width: 19px; }`];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 19
 * @framerIntrinsicHeight 20
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"DfxTrNMpt":"color","qfBdYY45Z":"strokeWidth"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Layout 2","color":{"type":"variable","value":"pxuiy5"},"set":{"localId":"vectorSet/oK4YxOh_L","id":"oK4YxOh_L","moduleId":"INkLaJAc0klouf5ZFBny"}}
 */
const Icon = withCSS(Component, css, "framer-1kqO8");
Icon.displayName = "Layout 2";
export default Icon;
addPropertyControls(Icon, {
    DfxTrNMpt: {
        defaultValue: 'var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(0, 0, 0)) /* {"name":"Black"} */',
        hidden: false,
        title: "Color",
        type: ControlType.Color
    },
    qfBdYY45Z: {
        defaultValue: 1.5,
        hidden: false,
        min: 0,
        title: "Stroke Width",
        type: ControlType.Number
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerVariables": "{\"DfxTrNMpt\":\"color\",\"qfBdYY45Z\":\"strokeWidth\"}",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "19",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerVector": "{\"name\":\"Layout 2\",\"color\":{\"type\":\"variable\",\"value\":\"pxuiy5\"},\"set\":{\"localId\":\"vectorSet/oK4YxOh_L\",\"id\":\"oK4YxOh_L\",\"moduleId\":\"INkLaJAc0klouf5ZFBny\"}}",
                "framerSupportedLayoutHeight": "any-prefer-fixed",
                "framerContractVersion": "1",
                "framerIntrinsicHeight": "20"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}