// Generated by Framer (571faa6)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const mask = 'url(\'data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 1.475 C 0 2.289 0.668 2.95 1.49 2.95 L 13.847 2.95 C 15.255 2.95 16.415 3.38 17.327 4.24 C 18.237 5.101 18.693 6.207 18.693 7.56 C 18.693 8.81 18.237 9.834 17.326 10.632 C 16.415 11.412 15.256 11.8 13.847 11.8 L 8.477 11.8 C 7.653 11.8 6.986 12.46 6.986 13.275 C 6.986 14.09 7.653 14.75 8.477 14.75 L 14.407 14.75 L 19.749 23.232 C 20.081 23.744 20.546 24 21.147 24 C 21.81 24 22.276 23.744 22.545 23.232 C 22.814 22.699 22.762 22.136 22.39 21.542 L 17.637 13.982 C 18.921 13.408 19.936 12.568 20.681 11.462 C 21.427 10.335 21.8 9.035 21.8 7.56 C 21.8 6.064 21.458 4.753 20.774 3.626 C 20.112 2.499 19.18 1.618 17.979 0.983 C 16.777 0.327 15.401 0 13.847 0 L 1.491 0 C 0.668 0 0 0.66 0 1.475 Z" fill="var(--12auh5f, var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0)))" height="24px" id="aJp5NyV9Y" transform="translate(0.643 0)" width="22.71414139081863px"/></svg>\') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)';
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(motion.div, { ...rest,
        layoutId: layoutId,
        ref: ref
    }) : /*#__PURE__*/ _jsx("div", { ...rest,
        ref: ref
    });
});
const getProps = ({
    color,
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        zZ3sDiGC9: color ? ? props.zZ3sDiGC9 ? ? "var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        zZ3sDiGC9,
        ...restProps
    } = getProps(props);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-gomDr", className),
        layoutId: layoutId,
        ref: ref,
        style: {
            "--12auh5f": zZ3sDiGC9,
            ...style
        }
    });
});
const css = [`.framer-gomDr { -webkit-mask: ${mask}; aspect-ratio: 1; background-color: var(--12auh5f); mask: ${mask}; width: 24px; }`];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"zZ3sDiGC9":"color"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Rive","color":{"type":"variable","value":"12auh5f"},"set":{"localId":"vectorSet/zWcoFJGye","id":"zWcoFJGye","moduleId":"foi8KRYmiUbaVeWDl4ta"}}
 */
const Icon = withCSS(Component, css, "framer-gomDr");
Icon.displayName = "Rive";
export default Icon;
addPropertyControls(Icon, {
    zZ3sDiGC9: {
        defaultValue: "var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
        hidden: false,
        title: "Color",
        type: ControlType.Color
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerImmutableVariables": "true",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerIntrinsicWidth": "24",
                "framerContractVersion": "1",
                "framerIntrinsicHeight": "24",
                "framerSupportedLayoutHeight": "any-prefer-fixed",
                "framerVector": "{\"name\":\"Rive\",\"color\":{\"type\":\"variable\",\"value\":\"12auh5f\"},\"set\":{\"localId\":\"vectorSet/zWcoFJGye\",\"id\":\"zWcoFJGye\",\"moduleId\":\"foi8KRYmiUbaVeWDl4ta\"}}",
                "framerVariables": "{\"zZ3sDiGC9\":\"color\"}"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}