// Generated by Framer (7c2f7bf)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    Instance,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "/framerusercontent.com/modules/2z1LAayU89TtN34qcAvL/WipFcG3Y6Git8QHrTVIe/xYEC_wF3E.js";
import Jira from "/framerusercontent.com/modules/lNH0tDOBde37KdhXfvGY/ybzRjw5z6zZdN4cfalxR/FTchGdtjO.js";
const enabledGestures = {
    pfYwMgBao: {
        hover: true
    }
};
const serializationHash = "framer-tw0DE";
const variantClassNames = {
    pfYwMgBao: "framer-v-1d3vdwe"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const nxpovt3KQ = undefined;
const QL4h8C77w = undefined;
const lSX_zlJoh = undefined;
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    logo,
    logoColor,
    tooltipText,
    width,
    ...props
}) => {
    return { ...props,
        lSX_zlJoh: tooltipText ? ? props.lSX_zlJoh ? ? "Figma",
        nxpovt3KQ: logoColor ? ? props.nxpovt3KQ ? ? "var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
        QL4h8C77w: logo ? ? props.QL4h8C77w ? ? Jira
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        lSX_zlJoh,
        QL4h8C77w,
        nxpovt3KQ,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "pfYwMgBao",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1d3vdwe", className, classNames),
                    "data-framer-name": "Tech Stack Logo",
                    layoutDependency: layoutDependency,
                    layoutId: "pfYwMgBao",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        "pfYwMgBao-hover": {
                            "data-framer-name": undefined
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-v93lqn",
                        "data-border": true,
                        "data-framer-name": "Tool Logo",
                        layoutDependency: layoutDependency,
                        layoutId: "t8fOh9AxU",
                        style: {
                            "--border-bottom-width": "1px",
                            "--border-color": "var(--token-e3a90888-763b-420f-bb27-f2520e07d9b1, rgb(222, 222, 222))",
                            "--border-left-width": "1px",
                            "--border-right-width": "1px",
                            "--border-style": "solid",
                            "--border-top-width": "1px",
                            backgroundColor: "var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255))",
                            borderBottomLeftRadius: 12,
                            borderBottomRightRadius: 12,
                            borderTopLeftRadius: 12,
                            borderTopRightRadius: 12,
                            boxShadow: "0px 0.5971439051427296px 0.5971439051427296px -0.9375px rgba(0, 0, 0, 0.07), 0px 1.8108796073283884px 1.8108796073283884px -1.875px rgba(0, 0, 0, 0.07), 0px 4.786990141113346px 4.786990141113346px -2.8125px rgba(0, 0, 0, 0.06), 0px 15px 15px -3.75px rgba(0, 0, 0, 0.03)"
                        },
                        children: /*#__PURE__*/ _jsx(Instance, {
                            animated: true,
                            className: "framer-4x0nzq",
                            Component: QL4h8C77w,
                            "data-framer-name": "Jira",
                            layoutDependency: layoutDependency,
                            layoutId: "rpo0HjlnP",
                            style: {
                                "--12auh5f": nxpovt3KQ
                            }
                        })
                    }), /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1xvo7ne",
                        "data-framer-name": "Tooltip",
                        layoutDependency: layoutDependency,
                        layoutId: "TqSk8psow",
                        style: {
                            backgroundColor: "var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
                            borderBottomLeftRadius: 1e3,
                            borderBottomRightRadius: 1e3,
                            borderTopLeftRadius: 1e3,
                            borderTopRightRadius: 1e3,
                            opacity: 0
                        },
                        transformTemplate: transformTemplate1,
                        variants: {
                            "pfYwMgBao-hover": {
                                opacity: 1
                            }
                        },
                        children: /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-455vy9",
                                    "data-styles-preset": "xYEC_wF3E",
                                    dir: "auto",
                                    style: {
                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255)))"
                                    },
                                    children: "Figma"
                                })
                            }),
                            className: "framer-9jnlh4",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "YIU185PLw",
                            style: {
                                "--extracted-r6o4lv": "var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255))",
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline"
                            },
                            text: lSX_zlJoh,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-tw0DE.framer-14pk0ym, .framer-tw0DE .framer-14pk0ym { display: block; }", ".framer-tw0DE.framer-1d3vdwe { align-content: center; align-items: center; cursor: default; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }", ".framer-tw0DE .framer-v93lqn { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 16px; position: relative; width: min-content; z-index: 2; }", ".framer-tw0DE .framer-4x0nzq { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }", ".framer-tw0DE .framer-1xvo7ne { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; left: 50%; overflow: hidden; padding: 4px 8px 4px 8px; pointer-events: none; position: absolute; top: -32px; width: min-content; will-change: var(--framer-will-change-override, transform); z-index: 1; }", ".framer-tw0DE .framer-9jnlh4 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-tw0DE.framer-v-1d3vdwe.hover .framer-9jnlh4 { -webkit-user-select: none; user-select: none; }", ...sharedStyle.css, '.framer-tw0DE[data-border="true"]::after, .framer-tw0DE [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 56
 * @framerIntrinsicWidth 56
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"HOuqDfPlj":{"layout":["auto","auto"]}}}
 * @framerVariables {"lSX_zlJoh":"tooltipText","QL4h8C77w":"logo","nxpovt3KQ":"logoColor"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerVectorSets ["foi8KRYmiUbaVeWDl4ta"]
 */
const FramerubaGHlmVl = withCSS(Component, css, "framer-tw0DE");
export default FramerubaGHlmVl;
FramerubaGHlmVl.displayName = "Tech Stack Logo";
FramerubaGHlmVl.defaultProps = {
    height: 56,
    width: 56
};
addPropertyControls(FramerubaGHlmVl, {
    lSX_zlJoh: {
        defaultValue: "Figma",
        description: "",
        displayTextArea: true,
        placeholder: "",
        title: "Tooltip Text",
        type: ControlType.String
    },
    onlSX_zlJohChange: {
        changes: "lSX_zlJoh",
        type: ControlType.ChangeHandler
    },
    QL4h8C77w: {
        defaultValue: {
            identifier: "local-module:vector/FTchGdtjO:default",
            moduleId: "lNH0tDOBde37KdhXfvGY"
        },
        description: "You can add your own icons by uploading svgs to this vector set located in the assets panel under vectors > project > toolstack icons",
        setModuleId: "foi8KRYmiUbaVeWDl4ta",
        title: "Logo",
        type: ControlType.VectorSetItem
    },
    nxpovt3KQ: {
        defaultValue: "var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
        title: "Logo color",
        type: ControlType.Color
    }
});
addFonts(FramerubaGHlmVl, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "/framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "/framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+1F00-1FFF",
        url: "/framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0370-03FF",
        url: "/framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "/framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "/framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "/framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerubaGHlmVl",
            "slots": [],
            "annotations": {
                "framerComponentViewportWidth": "true",
                "framerContractVersion": "1",
                "framerVectorSets": "[\"foi8KRYmiUbaVeWDl4ta\"]",
                "framerVariables": "{\"lSX_zlJoh\":\"tooltipText\",\"QL4h8C77w\":\"logo\",\"nxpovt3KQ\":\"logoColor\"}",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"HOuqDfPlj\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerColorSyntax": "true",
                "framerImmutableVariables": "true",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicWidth": "56",
                "framerAutoSizeImages": "true",
                "framerIntrinsicHeight": "56"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./ubaGHlmVl.map
