// Generated by Framer (62e4d63)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import SmallLogo from "/framerusercontent.com/modules/C6XU70YaOyOWmG4OwZdZ/CGx4Bzv6faYvlUC46nrM/ZTEGydyFL.js";
const SmallLogoFonts = getFonts(SmallLogo);
const cycleOrder = ["aTBCrc4Jk", "bAHFpmm1J", "ytrBCV0k8", "ZBuRmAZ5Y"];
const serializationHash = "framer-1Fjxh";
const variantClassNames = {
    aTBCrc4Jk: "framer-v-10c2ln6",
    bAHFpmm1J: "framer-v-h406hg",
    ytrBCV0k8: "framer-v-905gpi",
    ZBuRmAZ5Y: "framer-v-rjossz"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Variant 1": "aTBCrc4Jk",
    "Variant 2": "bAHFpmm1J",
    "Variant 3": "ytrBCV0k8",
    "Variant 4": "ZBuRmAZ5Y"
};
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "aTBCrc4Jk"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "aTBCrc4Jk",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-10c2ln6", className, classNames),
                    "data-framer-name": "Variant 1",
                    layoutDependency: layoutDependency,
                    layoutId: "aTBCrc4Jk",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        bAHFpmm1J: {
                            "data-framer-name": "Variant 2"
                        },
                        ytrBCV0k8: {
                            "data-framer-name": "Variant 3"
                        },
                        ZBuRmAZ5Y: {
                            "data-framer-name": "Variant 4"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 16,
                        y: (componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 16) - 0 - 16) / 2),
                        ...addPropertyOverrides({
                            bAHFpmm1J: {
                                y: (componentViewport ? .y || 0) + -15
                            },
                            ZBuRmAZ5Y: {
                                y: (componentViewport ? .y || 0) + -15
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-14g45mj-container",
                            "data-framer-name": "Orange",
                            layoutDependency: layoutDependency,
                            layoutId: "FM9FGfFPx-container",
                            name: "Orange",
                            nodeId: "FM9FGfFPx",
                            rendersWithMotion: true,
                            scopeId: "qOaUoYYIn",
                            children: /*#__PURE__*/ _jsx(SmallLogo, {
                                height: "100%",
                                id: "FM9FGfFPx",
                                layoutId: "FM9FGfFPx",
                                name: "Orange",
                                variant: "LAzaFDLEP",
                                width: "100%",
                                ...addPropertyOverrides({
                                    ytrBCV0k8: {
                                        variant: "LVxmklpu4"
                                    },
                                    ZBuRmAZ5Y: {
                                        variant: "LVxmklpu4"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 16,
                        y: (componentViewport ? .y || 0) + (componentViewport ? .height || 16) - 1,
                        ...addPropertyOverrides({
                            bAHFpmm1J: {
                                y: (componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 16) - 0 - 16) / 2)
                            },
                            ZBuRmAZ5Y: {
                                y: (componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 16) - 0 - 16) / 2)
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-d818a2-container",
                            "data-framer-name": "White",
                            layoutDependency: layoutDependency,
                            layoutId: "M0VhB_D0x-container",
                            name: "White",
                            nodeId: "M0VhB_D0x",
                            rendersWithMotion: true,
                            scopeId: "qOaUoYYIn",
                            children: /*#__PURE__*/ _jsx(SmallLogo, {
                                height: "100%",
                                id: "M0VhB_D0x",
                                layoutId: "M0VhB_D0x",
                                name: "White",
                                variant: "LVxmklpu4",
                                width: "100%",
                                ...addPropertyOverrides({
                                    ytrBCV0k8: {
                                        variant: "LAzaFDLEP"
                                    },
                                    ZBuRmAZ5Y: {
                                        variant: "LAzaFDLEP"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-1Fjxh.framer-6gbhy5, .framer-1Fjxh .framer-6gbhy5 { display: block; }", ".framer-1Fjxh.framer-10c2ln6 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: min-content; }", ".framer-1Fjxh .framer-14g45mj-container { flex: none; height: auto; position: relative; width: auto; }", ".framer-1Fjxh .framer-d818a2-container { bottom: -15px; flex: none; height: auto; left: -15px; position: absolute; width: auto; z-index: 1; }", ".framer-1Fjxh.framer-v-h406hg .framer-14g45mj-container, .framer-1Fjxh.framer-v-rjossz .framer-14g45mj-container { position: absolute; right: -15px; top: -15px; z-index: 1; }", ".framer-1Fjxh.framer-v-h406hg .framer-d818a2-container, .framer-1Fjxh.framer-v-rjossz .framer-d818a2-container { bottom: unset; left: unset; position: relative; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 16
 * @framerIntrinsicWidth 16
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"bAHFpmm1J":{"layout":["auto","auto"]},"ytrBCV0k8":{"layout":["auto","auto"]},"ZBuRmAZ5Y":{"layout":["auto","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerqOaUoYYIn = withCSS(Component, css, "framer-1Fjxh");
export default FramerqOaUoYYIn;
FramerqOaUoYYIn.displayName = "Logo animation";
FramerqOaUoYYIn.defaultProps = {
    height: 16,
    width: 16
};
addPropertyControls(FramerqOaUoYYIn, {
    variant: {
        options: ["aTBCrc4Jk", "bAHFpmm1J", "ytrBCV0k8", "ZBuRmAZ5Y"],
        optionTitles: ["Variant 1", "Variant 2", "Variant 3", "Variant 4"],
        title: "Variant",
        type: ControlType.Enum
    }
});
addFonts(FramerqOaUoYYIn, [{
    explicitInter: true,
    fonts: []
}, ...SmallLogoFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerqOaUoYYIn",
            "slots": [],
            "annotations": {
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"bAHFpmm1J\":{\"layout\":[\"auto\",\"auto\"]},\"ytrBCV0k8\":{\"layout\":[\"auto\",\"auto\"]},\"ZBuRmAZ5Y\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerColorSyntax": "true",
                "framerIntrinsicWidth": "16",
                "framerImmutableVariables": "true",
                "framerAutoSizeImages": "true",
                "framerIntrinsicHeight": "16",
                "framerContractVersion": "1",
                "framerComponentViewportWidth": "true",
                "framerDisplayContentsDiv": "false"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
