// Generated by Framer (dd59b2c)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    useSVGTemplate,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const mask = "var(--framer-icon-mask)";
const Base = /*#__PURE__*/ forwardRef(function(props, ref) {
    return /*#__PURE__*/ _jsx("svg", { ...props,
        ref: ref,
        children: props.children
    });
});
const MotionSVG = motion.create(Base);
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(MotionSVG, { ...rest,
        layoutId: layoutId,
        ref: ref,
        children: children
    }) : /*#__PURE__*/ _jsx("svg", { ...rest,
        ref: ref,
        children: children
    });
});
const svg = '<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 16 4.022 L 16 4 M 4 20 L 16 20 C 18.209 20 20 18.209 20 16 L 20 4 C 20 1.791 18.209 0 16 0 L 4 0 C 1.791 0 0 1.791 0 4 L 0 16 C 0 18.209 1.791 20 4 20 Z M 14.444 10 C 14.444 12.455 12.455 14.444 10 14.444 C 7.545 14.444 5.556 12.455 5.556 10 C 5.556 7.545 7.545 5.556 10 5.556 C 12.455 5.556 14.444 7.545 14.444 10 Z" fill="transparent" height="20px" id="SX1RGYN3B" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--1ww558a, 2)" stroke="var(--4rxgx6, black)" transform="translate(2 2)" width="20px"/></svg>';
const getProps = ({
    color,
    height,
    id,
    width,
    width1,
    ...props
}) => {
    return { ...props,
        CRY1Fpez4: color ? ? props.CRY1Fpez4 ? ? "rgb(0, 0, 0)",
        vet7gqNu_: width1 ? ? props.vet7gqNu_ ? ? 2
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        CRY1Fpez4,
        vet7gqNu_,
        ...restProps
    } = getProps(props);
    const href = useSVGTemplate("2660449837", svg);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-Hzxo3", className),
        layoutId: layoutId,
        ref: ref,
        role: "presentation",
        style: {
            "--1ww558a": vet7gqNu_,
            "--4rxgx6": CRY1Fpez4,
            ...style
        },
        viewBox: "0 0 24 24",
        children: /*#__PURE__*/ _jsx("use", {
            href: href
        })
    });
});
const css = [`.framer-Hzxo3 { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"CRY1Fpez4":"color","vet7gqNu_":"width1"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Instagram Social","color":{"type":"variable","value":"4rxgx6"},"set":{"localId":"vectorSet/dSZJyzeMx","id":"dSZJyzeMx","moduleId":"E1vFg1A6wcWAGuFi9Hz1"}}
 */
const Icon = withCSS(Component, css, "framer-Hzxo3");
Icon.displayName = "Instagram Social";
export default Icon;
addPropertyControls(Icon, {
    CRY1Fpez4: {
        defaultValue: "rgb(0, 0, 0)",
        hidden: false,
        title: "Color",
        type: ControlType.Color
    },
    vet7gqNu_: {
        defaultValue: 2,
        displayStepper: true,
        hidden: false,
        max: 4,
        min: 1,
        title: "Width",
        type: ControlType.Number
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerIntrinsicHeight": "24",
                "framerVector": "{\"name\":\"Instagram Social\",\"color\":{\"type\":\"variable\",\"value\":\"4rxgx6\"},\"set\":{\"localId\":\"vectorSet/dSZJyzeMx\",\"id\":\"dSZJyzeMx\",\"moduleId\":\"E1vFg1A6wcWAGuFi9Hz1\"}}",
                "framerSupportedLayoutHeight": "any-prefer-fixed",
                "framerImmutableVariables": "true",
                "framerVariables": "{\"CRY1Fpez4\":\"color\",\"vet7gqNu_\":\"width1\"}",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerIntrinsicWidth": "24"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}